### ISSUE TITLE
Uploading a new firmware clears the eeprom

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#27]
V1.2.0 pre

Uploading a new firmware clears the eeprom

When uploading a new firmware. This clears anything that was stored in the the eeprom (saved rhythms, sensitivity settings etc... )

In the future it would be important that people can update their module without loosing their progress and work

**Comment by lucblender** [comment]
I'm putting it as won't fix because it's right now it's not necessary. But I'm keeping it open to not forget it when doing a real update when the module will be out.

**Comment by lucblender** [comment]
Since [v1.11.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.11.0_pre), the eeprom management is done thanks to the eeprom version (major.minor.fix). If the major or minor version change, the whole memory is cleared. If only the fix change, the data stays. 
 
When adding or changing parameters linked to the eeprom, everything is done so it doesn't break the module and everything else in memory. --> And so trying to only change "fix" of the eeprom version.
