### ISSUE TITLE
Reset when next beat is 0 is inconsistent

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#40]
V1.6.0-pre

**Describe the bug or feature enhancement **
When sending a reset pulse every 16 beats right before the first beat of the bar. The module would hang a little and skip the first beat sometimes.

**If it's a bug: How to reproduce**
Here is signal I'm sending in. CH1 is CLK, CH2 is RST
![image](https://github.com/user-attachments/assets/949e3da3-b997-4a44-bee9-74267fb503e9)

**Expected behavior**

My suggestion would be that if a channel just played the last step of it rhythm it will ignore the reset signal. 

**Screenshots or Videos**

https://github.com/user-attachments/assets/8c0f8c90-e2f9-457e-90ff-fa010c20037a

**Comment by lucblender** [comment]
When doing reset, the rhythm counter goes to 0 and so the beat is not played. The inconsistency here is because the clock and reset are so close, the interrupt may pre-empt one or the other.

So that mean, for example, if you had your whole rhythm rotated by one (so first beat playing is the 2nd one), you wouldn't have this problem. 

So if we look in a more, general case, the problem is more that you do a reset and the first beat you have is enabled but won't be played.

So I see two solutions:
- the solution you suggest to no reset a rhythm that is at its end, that solve only that, but maybe it's enough
- or a more general solution where the first beat is played when doing a reset

I don't know if the more general solution is something good or not or if I should just stay with the solution you suggest, what's your opinion on this @ArthurGibert ?

**Comment by ArthurGibert** [comment]
Let's try the first one and see how it goes. 

Having the first beat play on reset might lead to some weird stuff if people use unquantized reset triggers.

**Comment by lucblender** [comment]
https://github.com/user-attachments/assets/7a2d74cb-d179-44b2-b4a7-510d7eb09dc9

@ArthurGibert I implemented what you suggested (or what I understood of your suggestion). But I don't think it's a good solution, here is why in a video. 

But basically if you have a one rhythm that is not the same length of the other that are 16 length, when doing your reset, that one rhythm will reset and not the others because they are located at their last beat. And so it will induce an offset of one beat.

**Comment by ArthurGibert** [comment]
Is the reset function on an interrupt? Because the behavior was
inconsistent in the 1.6.0 which could be due to some lag in processing the
reset impulse.

**Comment by ArthurGibert** [comment]
Sorry couldn't check the video before the I sent my previous message. Checked the video. I think I understood the problem. IMO a reset pulse should make it so that the next clock should play the first step and not immediately send the rhythm to the first step. 

Know what I mean?

**Comment by lucblender** [comment]
It pass by an interrupt but then pass through my event dispatcher, good point!

I will: 
1) make it more direct, no event dispatcher 
2) make reset go to first step without playing it (probably making the step grey so user has feedback it's in reset mode)

**Comment by ArthurGibert** [comment]
Let's try making it faster, I'm pretty confident that it should be enough.
It was working well most of the time already.

I wouldn't worry about visual feedback there. I think just having the
rhythms going to the first step should be enough.
